### ISSUE TITLE
Step error handling

### ISSUE THREAD

**Issue by andrewbutterfield** [andrewbutterfield/RTEMS-SMP-Formal#8]
How do we handle errors in the steps?

**Comment by GH-James** [comment]
Currently errors will cause output such as that below
This output makes sense to me

However, I wonder if this will be clear to users?
Would it make sense to remove the traceback, and instead show only the step/function that the error occurred?

```
Generating spin files for chains-api-model
gcc: error: chains-api-model.pl: No such file or directory
gcc: warning: ‘-x c’ after last input file has no effect
gcc: fatal error: no input files
compilation terminated.
spin: preprocessing failed
Traceback (most recent call last):
  File "/mnt/c/Users/jamsm/PycharmProjects/RTEMS-SMP-Formal/formal/promela/src/testbuilder.py", line 298, in <module>
    main()
  File "/mnt/c/Users/jamsm/PycharmProjects/RTEMS-SMP-Formal/formal/promela/src/testbuilder.py", line 268, in main
    run_all(sys.argv[2], config)
  File "/mnt/c/Users/jamsm/PycharmProjects/RTEMS-SMP-Formal/formal/promela/src/testbuilder.py", line 42, in run_all
    generate_spin_files(model, config["spinallscenarios"])
  File "/mnt/c/Users/jamsm/PycharmProjects/RTEMS-SMP-Formal/formal/promela/src/testbuilder.py", line 107, in generate_spin_files
    subprocess.run(f"spin {spinallscenarios} {model}.pl",
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'spin -DTEST_GEN -run -E -c0 -e chains-api-model.pl' returned non-zero exit status 1.
```

**Comment by andrewbutterfield** [comment]
Keep error messages user-friendly - no traceback required.
Focus on errors that would be caused by users.
